baseURL = ""
languageCode = "en-us"
title = "Josh Facts"
theme = "journal"
publishDir= "docs"

[params]
  description = "Blog meta description."
  githubUsername = "ankitjosh78"
  instagramUsername = "joshankit78"
  tagline = "A list of the best Josh facts (jokes). "
