baseURL = "https://google.com/"
languageCode = "en-us"
title = "Josh Facts"
theme = "journal"

[params]
  description = "Blog meta description."
  githubUsername = "ankitjosh78"
  twitterUsername = "josh_ankit"
  tagline = "A list of the best Josh facts (jokes). "
